version: 0.0
os: linux
files:
  - source: /
    destination: /webapps/FirstDevOps
hooks:
BeforeInstall:
    - location: /webapps/Scripts/stop.sh
AfterInstall:
    - location: /webapps/Scripts/start.sh
