version: 0.0
os: linux
files:
  - source: /
    destination: /webapps/FirstDevOps
hooks:
  BeforeInstall:
  - location: stop.sh
  AfterInstall:
  - location: install.sh
  ApplicationStart:
  - location: start.sh
  
